version: "3"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
        APP_MOUNT_URI: ${APP_MOUNT_URI}
        APPS_MARKETPLACE_API_URL: ${APPS_MARKETPLACE_API_URL}
        EXTENSIONS_API_URL: ${EXTENSIONS_API_URL}
        STATIC_URL: ${STATIC_URL}
        LOCALE_CODE: ${LOCALE_CODE}
        SKIP_SOURCEMAPS: ${SKIP_SOURCEMAPS}
    ports:
      - "3000:80"
